server:
  port: 80
#-----eureka------
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #是否从注册中心抓取一有信息，默认为true，集群必须为true
    fetch-registry: true
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka9528.com:9528/eureka/,http://eureka9529.com:9529/eureka/ #集群版