server:
  port: 9528
#------注册中心-------
eureka:
  instance:
    hostname: eureka9528.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，维护服务实例，不必去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka9529.com:9529/eureka/